# Generated by Django 5.0.4 on 2024-05-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsAndInventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
