services:
  db:
    image: postgres:latest
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=ProductAndInventoryDb
      - POSTGRES_USER=ProductAndInventory
      - POSTGRES_PASSWORD=Password123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    user: postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=ProductAndInventoryDb
      - POSTGRES_USER=ProductAndInventory
      - POSTGRES_PASSWORD=Password123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

volumes:
  db-data:
    driver: local